# Generated by Django 5.2.1 on 2025-11-15 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cuisine_type', models.CharField(blank=True, max_length=50, null=True)),
                ('price_range', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='中', max_length=1)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'restaurants',
                'indexes': [models.Index(fields=['cuisine_type'], name='idx_cuisine_type'), models.Index(fields=['price_range'], name='idx_price_range'), models.Index(fields=['is_active'], name='idx_is_active'), models.Index(fields=['city', 'district'], name='idx_city_district'), models.Index(fields=['latitude', 'longitude'], name='idx_geo_coordinates')],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='MerchantSideApp.restaurant')),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='MealTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MerchantSideApp.meal')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MerchantSideApp.tag')),
            ],
            options={
                'db_table': 'meal_tags',
                'unique_together': {('meal', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='meals', through='MerchantSideApp.MealTag', to='MerchantSideApp.tag'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['restaurant'], name='idx_meals_restaurant'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['category'], name='idx_category'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['is_vegetarian'], name='idx_is_vegetarian'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['is_available'], name='idx_is_available'),
        ),
    ]
