# Generated by Django 5.2.1 on 2025-11-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSideApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
