# Generated by Django 5.2.1 on 2025-11-27 21:23

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSideApp', '0003_alter_meal_created_at_alter_meal_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_account', to='MerchantSideApp.restaurant')),
            ],
            options={
                'db_table': 'merchant_accounts',
                'indexes': [models.Index(fields=['email'], name='idx_merchant_email')],
            },
        ),
    ]
