# Generated by Django 5.2.1 on 2025-11-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSideApp', '0004_merchantaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantaccount',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
