# Generated by Django 5.2.1 on 2025-11-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSideApp', '0005_nutritioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
