# Generated by Django 5.2.1 on 2025-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSideApp', '0006_merchantaccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantaccount',
            name='merchant_name',
            field=models.CharField(blank=True, help_text='Human-friendly merchant handle used during login.', max_length=50, null=True, unique=True),
        ),
    ]
