# Generated by Django 5.2.1 on 2025-11-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MerchantSideApp", "0007_merchantaccount_merchant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="image_file",
            field=models.ImageField(blank=True, null=True, upload_to="meals/photos/"),
        ),
    ]
