# Generated by ChatGPT on 2025-11-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MerchantSideApp", "0008_meal_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritioninfo",
            name="breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
