# Generated by Django 5.2.1 on 2025-11-15 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MerchantSideApp', '0001_initial'),
        ('UserSideApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('was_selected', models.BooleanField(default=False)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='MerchantSideApp.meal')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='MerchantSideApp.restaurant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='UserSideApp.appuser')),
            ],
            options={
                'db_table': 'recommendation_history',
                'indexes': [models.Index(fields=['user'], name='idx_rec_history_user'), models.Index(fields=['recommended_at'], name='idx_recommended_at')],
            },
        ),
    ]
