# Generated by Django 5.2.1 on 2025-11-15 22:52

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationhistory',
            name='recommended_at',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AlterField(
            model_name='recommendationhistory',
            name='was_selected',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
