# Generated by Django 5.2.1 on 2025-11-17 13:35

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSideApp', '0003_alter_meal_created_at_alter_meal_is_available_and_more'),
        ('UserSideApp', '0002_alter_appuser_created_at_alter_appuser_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '點心')], max_length=16)),
                ('meal_name', models.CharField(max_length=100)),
                ('calories', models.DecimalField(decimal_places=2, help_text='kcal', max_digits=6)),
                ('protein_grams', models.DecimalField(decimal_places=2, default=0, help_text='g', max_digits=6)),
                ('carb_grams', models.DecimalField(decimal_places=2, default=0, help_text='g', max_digits=6)),
                ('fat_grams', models.DecimalField(decimal_places=2, default=0, help_text='g', max_digits=6)),
                ('meal_notes', models.TextField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, help_text='List of ingredients or components with quantities.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('source_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_meal_records', to='MerchantSideApp.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='UserSideApp.appuser')),
            ],
            options={
                'db_table': 'daily_meal_records',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('meal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='UserSideApp.dailymealrecord')),
            ],
            options={
                'db_table': 'meal_components',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('breakfast', '早餐提醒'), ('lunch', '午餐提醒'), ('dinner', '晚餐提醒'), ('snack', '點心提醒'), ('random', '隨機推薦')], max_length=20)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('channel', models.CharField(choices=[('push', '推播'), ('email', 'Email'), ('sms', 'SMS')], default='push', max_length=10)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='UserSideApp.appuser')),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('sent', '已發送'), ('read', '已讀'), ('failed', '失敗')], default='sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('extra_payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='UserSideApp.appuser')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='UserSideApp.notificationsetting')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyIntakeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Week start date (Monday).')),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_carbs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_fat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meal_count', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_intake', to='UserSideApp.appuser')),
            ],
            options={
                'db_table': 'weekly_intake_summaries',
            },
        ),
        migrations.AddIndex(
            model_name='dailymealrecord',
            index=models.Index(fields=['user', 'date'], name='idx_meal_user_date'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymealrecord',
            unique_together={('user', 'date', 'meal_type', 'meal_name')},
        ),
        migrations.AddIndex(
            model_name='mealcomponent',
            index=models.Index(fields=['meal_record'], name='idx_component_record'),
        ),
        migrations.AddIndex(
            model_name='notificationsetting',
            index=models.Index(fields=['user'], name='idx_notify_settings_user'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsetting',
            unique_together={('user', 'reminder_type')},
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user'], name='idx_notify_log_user'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='idx_notify_log_status'),
        ),
        migrations.AddIndex(
            model_name='weeklyintakesummary',
            index=models.Index(fields=['user', 'week_start'], name='idx_weekly_user'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyintakesummary',
            unique_together={('user', 'week_start')},
        ),
    ]
