# Generated by Django 5.2.1 on 2025-11-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MerchantSideApp', '0004_merchantaccount'),
        ('UserSideApp', '0003_dailymealrecord_mealcomponent_notificationsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcomponent',
            name='meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_components', to='MerchantSideApp.meal'),
        ),
        migrations.AlterField(
            model_name='mealcomponent',
            name='meal_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='UserSideApp.dailymealrecord'),
        ),
        migrations.AddIndex(
            model_name='mealcomponent',
            index=models.Index(fields=['meal'], name='idx_component_meal'),
        ),
    ]
