# Generated by Django 5.2.1 on 2025-11-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSideApp', '0004_mealcomponent_meal_alter_mealcomponent_meal_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
