# Generated by Django 5.2.1 on 2025-11-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserSideApp", "0005_appuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
