# Generated by Django 5.2.1 on 2025-11-30 18:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSideApp', '0006_userpreference_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='recommendation_cooldown_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cooldown days before recommending the same meal again.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
